name: Docker Image CI/CD
on:
  push:
      branches: [ "main" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: action/checkout@v4
      - name: Build the Docker image
        run: docker build -t my-monitor-image .
